spring :
   datasource :
       url  : jdbc:mysql://localhost:3306/hibernate
       username : root
       password : root
       driver-class: com.mysql.jdbc.Driver
   jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update