/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'SINGH.BHARAT' at '10/15/16 5:10 PM' with Gradle 2.14.1
 *
 * @author SINGH.BHARAT, @date 10/15/16 5:10 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
