package org.eagle.spring;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'SINGH.BHARAT' at '8/25/16 3:41 PM' with Gradle 2.14
 *
 * @author SINGH.BHARAT, @date 8/25/16 3:41 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
